pipeline{
 	agent any
 	
 	tools{
 		jdk "javaJdk"
 	}
 	
 	 stages {
 	 
        stage('Build') {
            steps {
	            echo 'Hello user, Here building the code'
	            dir ('demo-project'){
	            	bat 'ant build'
	            }
        	}
     	}
     
     
     	stage('warfile'){
     		steps{
     			echo 'War file generating'
	     		dir('demo-project'){
	     			bat 'ant warTarget'
	     		}
	     	}	
     	}
     
     
     	stage('Deploy'){
     		steps{
	     		echo 'deploy the war project'
	     		bat 'ant deploy'
     		}
     	}
     	
     }
}